name: Build

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '16.x'

jobs:
  build-and-test:
    name: Build and test
    uses: ./.github/workflows/build-and-test.yml
    with:
      NODE_VERSION: $NODE_VERSION
