name: Merge

on:
  push:
    branches:
      - main

jobs:
  update_changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Commitzen
        run: |
          python -m pip install --upgrade pip
          pip install -U Commitizen

      - name: Update Changelog
        run: cz changelog

      - name: Commit and Push Changes to Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update changelog'
          commit_options: '--no-verify --signoff'
          file_pattern: 'CHANGELOG.md'

  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install Node Modules
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:cov

  check_commit_messages:
    name: Check Commit Messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Commitzen
        run: |
          python -m pip install --upgrade pip
          pip install -U Commitizen

      - name: Check Commit Messages
        run: cz check --rev-range HEAD
