name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '16.x'

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      NODE_VERSION: $NODE_VERSION
