name: Release

on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: '16.x'
          cache: 'npm'

      - name: Install Node Modules
        run: npm ci

      - name: Build
        run: npm run build

      - name: Bump Version
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          changelog_increment_filename: RELEASE_NOTES.md
          commit: false
          push: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Version
        run: echo "Bumping to version ${{ steps.cz.outputs.version }}"

      - name: Update package-lock.json
        run: npm i --package-lock-only

      - name: Push changes to repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: release ${{ steps.cz.outputs.version }}'
          commit_options: '--no-verify --signoff'
          file_pattern: cz.json package.json package-lock.json CHANGELOG.md
          tagging_message: '${{ steps.cz.outputs.version }}'

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          npm pack
          npm publish --verbose --access public

      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'solec-ic-webpack-plugin-${{ steps.cz.outputs.version }}.tgz'
          bodyFile: 'RELEASE_NOTES.md'
          tag: '${{ steps.cz.outputs.version }}'
          commit: 'main'


